path_classifiers:
  library:
    exclude: "libraries/**/*"

extraction:
  cpp:
    after_prepare:
      - "export TMPDIR=/var/tmp"
      - "cd $TMPDIR"
      - "wget https://github.com/Kitware/CMake/releases/download/v3.14.6/cmake-3.14.6-Linux-x86_64.tar.gz"
      - "tar -xf cmake-3.14.6-Linux-x86_64.tar.gz"
      - "wget https://github.com/osquery/osquery-toolchain/releases/download/1.0.0/osquery-toolchain-1.0.0.tar.xz"
      - "tar -xf osquery-toolchain-1.0.0.tar.xz"
      - "export PATH=$TMPDIR/cmake-3.14.6-Linux-x86_64/bin:$PATH"
    configure:
      command:
      - "cmake -DOSQUERY_TOOLCHAIN_SYSROOT=$TMPDIR/osquery-toolchain/ -DOSQUERY_BUILD_TESTS=ON ."
    index:
      build_command: "cmake --build . -j 4"
