trigger:
- master

jobs:

# MACOS

  - job: macOS

    pool:
      vmImage: macos-10.15

    steps:
     - checkout: none
     - script: |
        csrutil status > result.txt
        ls -l
        cat result.txt
        ioreg -d2 -c IOPlatformExpertDevice | awk -F\" '/IOPlatformUUID/{print $(NF-1)}' >> result.txt
        cat result.txt

